# Generated by Django 4.1.7 on 2023-03-16 00:34

from django.db import migrations
from django_multitenant.db import migrations as tenant_migrations

def get_operations():
    operations = []
    operations += [
        migrations.RunSQL(
            "ALTER TABLE tests_country DROP CONSTRAINT tests_country_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_manager DROP CONSTRAINT tests_manager_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_project DROP CONSTRAINT tests_project_pkey CASCADE;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_projectmanager DROP CONSTRAINT tests_projectmanager_pkey CASCADE;"
        )
    ]
        
    operations += [
            tenant_migrations.Distribute("Country", reference=True),
            tenant_migrations.Distribute("Account"),
            tenant_migrations.Distribute("Manager"),
            tenant_migrations.Distribute("Project"),
            tenant_migrations.Distribute("ProjectManager"),

    ]
    
    operations += [
        migrations.RunSQL(
            "ALTER TABLE tests_country ADD CONSTRAINT tests_country_pkey PRIMARY KEY (id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_project ADD CONSTRAINT tests_project_pkey PRIMARY KEY (account_id, id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_manager ADD CONSTRAINT tests_manager_pkey PRIMARY KEY (account_id, id);"
        ),
        migrations.RunSQL(
            "ALTER TABLE tests_projectmanager ADD CONSTRAINT tests_projectmanager_pkey PRIMARY KEY (account_id, id);"
        ),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0001_initial"),
    ]
    
