# Generated by Django 4.1.5 on 2023-01-19 15:15

from django.db import migrations
from ..models import (
    Country,
    Manager,
    Project,
    ProjectManager,
    Account
)

from django.contrib.auth.models import User


def forwards_func(apps, schema_editor):

    db_alias = schema_editor.connection.alias
    Country.objects.using(db_alias).bulk_create(
        [
            Country(name="USA"),
            Country(name="France"),
            Country(name="Turkiye"),
        ]
    )

    user_tr = User.objects.create_user(
        username="turkiye_user", email="turkiye@gmail.com", password="password"
    )

    user_us = User.objects.create_user(
        username="usa_user", email="us@gmail.com", password="password"
    )

    user_fr = User.objects.create_user(
        username="fr_user", email="fr@gmail.com", password="password"
    )

    Account.objects.using(db_alias).bulk_create(
        [
            Account(
                user=user_us,
                name="johndoe",
                domain="domain",
                subdomain="subdomain",
                country=Country.objects.get(name="USA"),
            ),
            Account(
                user=user_us,
                name="jilldoe",
                domain="domain",
                subdomain="subdomain",
                country=Country.objects.get(name="USA"),
            ),
            Account(
                user=user_us,
                name="milldoe",
                domain="domain",
                subdomain="subdomain",
                country=Country.objects.get(name="USA"),
            ),
            Account(
                user=user_tr,
                name="alidoe",
                domain="domain",
                subdomain="subdomain",
                country=Country.objects.get(name="Turkiye"),
            ),
            Account(
                user=user_tr,
                name="velidoe",
                domain="domain",
                subdomain="subdomain",
                country=Country.objects.get(name="Turkiye"),
            ),
            Account(
                user=user_fr,
                name="pierredoe",
                domain="domain",
                subdomain="subdomain",
                country=Country.objects.get(name="France"),
            ),
        ]
    )

    Manager.objects.using(db_alias).bulk_create(
        [
            Manager(name="John Doe", account=Account.objects.get(name="johndoe")),
            Manager(name="Ali Doe", account=Account.objects.get(name="alidoe")),
        ]
    )

    Project.objects.using(db_alias).bulk_create(
        [
            Project(name="Project US", account=Account.objects.get(name="johndoe")),
            Project(name="Project TR", account=Account.objects.get(name="alidoe")),
        ]
    )

    ProjectManager.objects.using(db_alias).bulk_create(
        [
            ProjectManager(
                project=Project.objects.get(name="Project US"),
                manager=Manager.objects.get(name="John Doe"),
                account=Account.objects.get(name="johndoe"),
            ),
            ProjectManager(
                project=Project.objects.get(name="Project TR"),
                manager=Manager.objects.get(name="Ali Doe"),
                account=Account.objects.get(name="alidoe"),
            ),
        ]
    )


def reverse_func(apps, schema_editor):


    ProjectManager.objects.all().delete()
    Project.objects.all().delete()
    Manager.objects.all().delete()
    Account.objects.all().delete()
    Country.objects.all().delete()
    User.objects.get(username="anonymous").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quickstart", "0002_distribute"),
    ]

    operations = [migrations.RunPython(forwards_func, reverse_func)]
